name: Coverage report

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed


jobs:
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest

    if: github.event.workflow_run.event == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.pull_requests[0].head.sha }}

      - name: 'Download artifact'
        id: prepare_report
        uses: actions/github-script@v6
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });

            let matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "codecov-report";
            });

            if (matchArtifact && matchArtifact[0]) {
              let found = matchArtifact[0];

              core.setOutput('override_sha', matchArtifact[0].workflow_run.head_sha);
              core.setOutput('override_branch', matchArtifact[0].workflow_run.head_branch);
              core.setOutput('override_build', matchArtifact[0].workflow_run.id);

              var download = await github.rest.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: found.id,
                 archive_format: 'zip',
              });
              var fs = require('fs');
              fs.writeFileSync('${{github.workspace}}/codecov-report.zip', Buffer.from(download.data));
            } else {
              console.error('No artifact found');
            }

      - run: unzip codecov-report.zip

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov-report.json
          fail_ci_if_error: true
          override_commit: ${{ github.event.workflow_run.pull_requests[0].head.sha }}
          override_pr: ${{ github.event.workflow_run.pull_requests[0].number }}
