name: Coverage report

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
  FORCE_COLOR: 3

jobs:
  coverage:
    name: Coverage report
    runs-on: ubuntu-latest

    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v6
        with:
          script: |
            var artifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            console.log(`I am here with ${context.payload.workflow_run.id}`);
            // console.log(JSON.stringify(artifacts));

            var matchArtifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "codecov-report";
            });
            console.log("I am there");
            console.log(JSON.stringify(matchArtifact));

            console.log("workflow run is");
            console.log(JSON.stringify(context.payload.workflow_run));

            var download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact[0].id,
               archive_format: 'zip',
            });
            var fs = require('fs');
            fs.writeFileSync('${{github.workspace}}/codecov-report.zip', Buffer.from(download.data));
      - run: unzip codecov-report.zip

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov-report.json
          fail_ci_if_error: true
